-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/004_figsy_crm_deal.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- F2-2: CRM deal push on interested reply
-- Track which enrollments have been pushed to CRM as a deal/opportunity

alter table public.figsy_enrollments
  add column if not exists crm_deal_id    text,
  add column if not exists crm_pushed_at  timestamptz;
