-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/010_crm_dedup.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- CRM dedup: never cold-email a client's existing customers / known contacts.
-- Read-only check against the client's own CRM (HubSpot/Pipedrive) before FIGSY
-- enrolls a lead. Reuses crm_type + crm_api_key from 003_crm_integration.

-- Per-client toggle (separate from crm_sync_enabled: dedup is READ, sync is WRITE).
alter table public.clients
  add column if not exists crm_dedup_enabled boolean not null default false;

-- Flag + reason on leads so the dedup result is visible in the portal and we
-- never re-spend credits re-checking the same lead.
alter table public.leads
  add column if not exists crm_existing     boolean not null default false,
  add column if not exists crm_match_reason text;

-- Fast lookup of already-flagged leads.
create index if not exists idx_leads_crm_existing
  on public.leads (client_id) where crm_existing = true;
