-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/011_denise.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Denise — The Closer (AI Account Executive) — migration 011
-- Safe to re-run. Adds 'denise' as a sellable subscription product and a table
-- to persist the drafts (follow-ups + proposals) Denise generates for clients.

-- ─────────────────────────────────────────────
-- 1. Allow 'denise' as a subscription product
--    (the inline check from schema.sql only allowed lead_gen / lead_gen_figsy
--     / virtual_assistant / chatbot)
-- ─────────────────────────────────────────────
alter table public.subscriptions
  drop constraint if exists subscriptions_product_check;

alter table public.subscriptions
  add constraint subscriptions_product_check
  check (product in (
    'lead_gen', 'lead_gen_figsy', 'figsy_addon',
    'virtual_assistant', 'chatbot', 'denise', 'denise_addon'
  ));

-- ─────────────────────────────────────────────
-- 2. Denise drafts — every follow-up / proposal she writes for a client
-- ─────────────────────────────────────────────
create table if not exists public.denise_drafts (
  id           uuid        primary key default gen_random_uuid(),
  client_id    uuid        not null references public.clients(id) on delete cascade,
  kind         text        not null check (kind in ('follow_up', 'proposal')),
  -- the structured input the client gave Denise (prospect/company/call summary)
  input        jsonb       not null default '{}'::jsonb,
  -- the draft Denise produced
  output       text        not null,
  created_at   timestamptz not null default now()
);

create index if not exists idx_denise_drafts_client_id on public.denise_drafts(client_id);
create index if not exists idx_denise_drafts_created_at on public.denise_drafts(created_at desc);

alter table public.denise_drafts enable row level security;

-- Clients can read their own drafts
drop policy if exists denise_drafts_client_read on public.denise_drafts;
create policy denise_drafts_client_read
  on public.denise_drafts for select
  using (client_id in (select id from public.clients where user_id = auth.uid()));

-- Service role full access (the API writes drafts on the client's behalf)
drop policy if exists denise_drafts_service_all on public.denise_drafts;
create policy denise_drafts_service_all
  on public.denise_drafts for all to service_role using (true) with check (true);
