-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/012_signer_and_booking.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Migration 012 — configurable email sign-off name (P-a) + booking link field (CAL-min)
-- Run once against Supabase (SQL Editor). Additive + idempotent — safe to re-run.
--
-- P-a: clients can set the exact name FIGSY signs outreach as, instead of FIGSY
--      inventing a South-African-sounding first name. NULL = keep old behaviour.
-- CAL-min: booking_url already exists in most environments; added here defensively
--      so non-Google clients can paste any booking link (Calendly/Zoho/etc.).

alter table public.clients
  add column if not exists signer_name text,
  add column if not exists booking_url text;
