-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260602_figsy_chat_history.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- FIGSY chat history — server-side persistence for the AskFigsyButton thread.
-- Without this table the chat still works (localStorage), but the thread is
-- lost on cache-clear or a different device. With it, the thread follows the
-- user everywhere. The API degrades gracefully if this table is absent.

create table if not exists public.figsy_chat_messages (
  id         uuid primary key default uuid_generate_v4(),
  client_id  uuid not null references public.clients(id) on delete cascade,
  role       text not null check (role in ('user','assistant')),
  content    text not null,
  created_at timestamptz not null default now()
);

create index if not exists figsy_chat_messages_client_idx
  on public.figsy_chat_messages (client_id, created_at);

alter table public.figsy_chat_messages enable row level security;

-- Service role (API) bypasses RLS. No direct client access — all reads/writes
-- go through the authenticated API which scopes by client_id.
