-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260724_vida_rebook_count.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- #499m — no-show → rebook×2 → keep the $3. Idempotent. Run once in Supabase
-- (staging → prod). NON-MONEY: the $3 is captured at booking (calendar.ts:198) and is
-- KEPT on a no-show — no refund path fires. This column only tracks how many goodwill
-- rebooks a client has been given so the operator console can stop offering more after 2.
alter table public.calendar_bookings add column if not exists rebook_count int not null default 0;
