-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260722_review_gate_producer.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- #15 — wire the co-pilot (review_required) gate to a real producer + approval send.
-- The approval queue previously had no producer and no send-on-approve; the send path
-- now enqueues drafts here when a campaign is in co-pilot mode, and the approve endpoint
-- re-enters the send path to actually deliver. That re-entry needs the enrollment +
-- sequence context, so the queue row must carry it.
ALTER TABLE public.figsy_approval_queue
  ADD COLUMN IF NOT EXISTS enrollment_id  UUID,
  ADD COLUMN IF NOT EXISTS total_steps    INTEGER,
  ADD COLUMN IF NOT EXISTS wait_days_next INTEGER;

-- One PENDING review row per enrollment-step: a re-run of the same step (overlapping
-- cron / manual send-now) must not pile up duplicate drafts. Partial unique index over
-- pending rows only, so approved/sent/rejected history is unaffected.
CREATE UNIQUE INDEX IF NOT EXISTS uq_approval_pending_enrollment_step
  ON public.figsy_approval_queue(enrollment_id, sequence_step)
  WHERE status = 'pending';
