-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260602_calendar_bookings.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Calendar bookings — records a real meeting created on a client's connected
-- Google Calendar via POST /calendar/book. Without this table that endpoint
-- 500s on insert. Also the anchor for tying a booking back to the lead and
-- the FIGSY enrollment that produced it.

create table if not exists public.calendar_bookings (
  id              uuid primary key default uuid_generate_v4(),
  client_id       uuid not null references public.clients(id) on delete cascade,
  lead_id         uuid references public.leads(id) on delete set null,
  enrollment_id   uuid references public.figsy_enrollments(id) on delete set null,
  google_event_id text,
  meeting_title   text,
  start_time      timestamptz,
  end_time        timestamptz,
  meeting_link    text,
  status          text not null default 'confirmed',
  created_at      timestamptz not null default now()
);

create index if not exists calendar_bookings_client_idx
  on public.calendar_bookings (client_id, start_time);
create index if not exists calendar_bookings_lead_idx
  on public.calendar_bookings (lead_id);

alter table public.calendar_bookings enable row level security;
-- Service role (API) only — all access scoped by client_id in the API layer.
