-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260724_booking_unique_guard.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- Audit fix (M6) — enforce the "one active confirmed booking per (client, lead)" invariant at
-- the DB level so two concurrent /book requests can't both insert a confirmed row (the app-level
-- read-then-insert check is TOCTOU-racy). Idempotent. Run once in Supabase (staging → prod).
-- NON-MONEY (capture is already idempotent); this just stops duplicate calendar_bookings rows.
--
-- NOTE: if legacy duplicate confirmed rows already exist this index creation will fail — dedupe
-- them first (keep the earliest per client+lead). Safe/no-op on a clean table.
create unique index if not exists calendar_bookings_one_confirmed_per_lead
  on public.calendar_bookings (client_id, lead_id)
  where status = 'confirmed';
