-- ═══════════════════════════════════════════════════════════════════════════════
-- 🪦 SUPERSEDED 31 Jul 2026 (#273) — the live copy is supabase/migrations/20260724_nexus_autotune_flag.sql
-- ═══════════════════════════════════════════════════════════════════════════════
-- DO NOT EDIT THIS FILE, and do not add new migrations to this directory.
--
-- This file is KEPT, not deleted (CORE-MAP rule 3, founder-locked: nothing gets deleted).
-- It is here as the record of where this migration originally lived. Every migration now
-- has exactly one home — `supabase/migrations/` — and this directory's README says why.
--
-- The body below is identical to the canonical copy, and a test enforces that. If you need
-- to change this migration, change the canonical file; if you need to change what the
-- product RUNS, change `apps/api/src/lib/pending-migrations.ts`.
-- ═══════════════════════════════════════════════════════════════════════════════

-- #511 NEXUS · Phase 3 — the per-client auto-tune KILL-SWITCH. Idempotent. Run once in
-- Supabase (staging → prod). NON-MONEY (a boolean flag), but it GOVERNS money-sensitive
-- Phase-2 sourcing tuning: auto-tune is OFF by default for every client — the founder
-- explicitly enables it per client once they trust that client's Nexus. Default-deny.
alter table public.clients add column if not exists nexus_autotune_enabled boolean not null default false;
