// Apollo.io people search — maps ICP criteria to API params and normalises results

// Apollo's PUBLIC REST API is under /api/v1. The bare /v1 host is Apollo's internal
// web API (session/OAuth) — calling it with an X-Api-Key is accepted but runs
// without account context, returning HTTP 200 with zero results. Must be /api/v1.
const APOLLO_BASE = 'https://api.apollo.io/api/v1'
// People search endpoint. /mixed_people/search is deprecated for API callers (422);
// the supported path is /mixed_people/api_search (no-credit, net-new prospecting).
// Ref: https://docs.apollo.io/reference/people-api-search
const APOLLO_PEOPLE_SEARCH = `${APOLLO_BASE}/mixed_people/api_search`

// ── Seniority mapping ─────────────────────────────────────────────────────────
const SENIORITY_MAP: Record<string, string[]> = {
  'C-Suite':                ['c_suite'],
  'VP / Director':          ['vp', 'director'],
  'Head of':                ['head'],
  'Manager':                ['manager'],
  'Senior':                 ['senior'],
  'Individual Contributor': ['entry'],
}

// ── Company size mapping (Apollo uses "min,max" ranges) ───────────────────────
const EMPLOYEE_RANGE_MAP: Record<string, string> = {
  '1–10':      '1,10',
  '11–50':     '11,50',
  '51–200':    '51,200',
  '201–500':   '201,500',
  '501–1,000': '501,1000',
  '1,000+':    '1001,1000000',
}

// Resolve a company-size label to an Apollo "min,max" range. Tolerant of dash type
// (– vs -), thousands separators, and lower-bound drift — the conversational ICP
// builder is an LLM and emits variants like "2–10" that won't hit the exact map.
// Without this, an unmatched label was silently dropped from the search.
function toEmployeeRange(size: string): string | null {
  if (EMPLOYEE_RANGE_MAP[size]) return EMPLOYEE_RANGE_MAP[size]
  const cleaned = size.replace(/,/g, '').trim()
  const nums = cleaned.match(/\d+/g)?.map(Number) ?? []
  if (/\+\s*$/.test(cleaned) && nums.length >= 1) return `${nums[0]},1000000`
  if (nums.length >= 2) return `${nums[0]},${nums[1]}`
  if (nums.length === 1) return `${nums[0]},${nums[0]}`
  return null
}

export interface ApolloContact {
  id: string
  first_name: string
  last_name:  string
  email:      string | null
  email_status: string | null   // 'verified' | 'unverified' | 'likely_to_engage' | etc.
  linkedin_url: string | null
  title:       string | null
  seniority:   string | null
  country:     string | null
  organization_name: string | null
  organization: {
    name:              string | null
    num_employees:     number | null
    industry:          string | null
    technology_names:  string[]
  } | null
}

interface ApolloSearchBody {
  page:     number
  per_page: number
  person_titles?:                      string[]
  person_seniorities?:                 string[]
  organization_num_employees_ranges?:  string[]
  person_locations?:                   string[]
  contact_email_status?:               string[]
  q_keywords?:                         string
  organization_latest_funding_stage_cd?: string[]
  q_organization_keyword_tags?:          string[]
  organization_names?:                   string[]
}

// Build the search body from an ICP record
export function buildSearchBody(icp: {
  job_titles:            string[]
  seniority_levels:      string[]
  company_sizes:         string[]
  geographies:           string[]
  industries:            string[]
  tech_stack:            string[]
  keywords:              string[]
  apollo_only_consented: boolean
  intent_signals?:       string[]
  organization_names?:   string[]
}, page = 1): ApolloSearchBody {
  const body: ApolloSearchBody = { page, per_page: 50 }

  if (icp.job_titles.length)
    body.person_titles = icp.job_titles

  const seniorities = icp.seniority_levels.flatMap(s => SENIORITY_MAP[s] ?? [])
  if (seniorities.length)
    body.person_seniorities = seniorities

  const employeeRanges = icp.company_sizes.map(toEmployeeRange).filter((r): r is string => r !== null)
  if (employeeRanges.length)
    body.organization_num_employees_ranges = employeeRanges

  if (icp.geographies.length)
    body.person_locations = icp.geographies

  // Apollo's verified/likely_to_engage emails are the closest proxy for consent
  if (icp.apollo_only_consented)
    body.contact_email_status = ['verified', 'likely_to_engage']

  // Industries → Apollo's organization keyword-tag field (OR semantics across tags).
  // These MUST NOT go into q_keywords: that field is a literal full-text match, so
  // space-joining industries collapses the result set to near-zero (e.g.
  // "SaaS Consulting" returns 1 person, vs 65k via q_organization_keyword_tags).
  if (icp.industries.length)
    body.q_organization_keyword_tags = icp.industries

  // tech_stack is deliberately NOT sent to Apollo. It is auto-generated by the
  // conversational ICP builder as free text (e.g. "Email outreach tools", "CRM"),
  // which are not valid Apollo technology UIDs — applying them as a technology
  // filter zeroes the search. A validated tech picker can reintroduce this later.

  // icp.keywords is deliberately NOT sent to Apollo. q_keywords is a LITERAL
  // full-text match across the whole profile, so multi-word values collapse the
  // result set to ~0 (e.g. the conversational builder emits prose like
  // "manual outreach pipeline building sales scaling…", which matches nobody).
  // The structured filters above (titles, seniority, industry tags, geo, size)
  // are what actually target. Keyword/intent targeting belongs in the OR-based
  // q_organization_keyword_tags, handled for intent signals below.

  // Intent signals
  if (icp.intent_signals && icp.intent_signals.length > 0) {
    const fundingStages: string[] = []
    const orgKwTags: string[] = []

    for (const signal of icp.intent_signals) {
      if (signal === 'recently_funded') {
        fundingStages.push('seed', 'series_a', 'series_b', 'series_c', 'series_d')
      }
      if (signal === 'hiring_sdrs') {
        orgKwTags.push('hiring sales development')
      }
      if (signal === 'headcount_growth') {
        orgKwTags.push('growing team')
      }
      if (signal === 'new_executive') {
        orgKwTags.push('new ceo new cto new vp')
      }
    }

    if (fundingStages.length) body.organization_latest_funding_stage_cd = fundingStages
    // Intent keyword tags OR into the org keyword-tag field (NOT literal q_keywords),
    // so they widen rather than collapse the search.
    if (orgKwTags.length)
      body.q_organization_keyword_tags = [...(body.q_organization_keyword_tags ?? []), ...orgKwTags]
  }

  // ABM — named account targeting
  if (icp.organization_names && icp.organization_names.length > 0)
    body.organization_names = icp.organization_names

  return body
}

// Returns total matching leads for an ICP (uses per_page:1 to minimise credit use).
// Returns a diagnostic envelope — NOT a bare 0 — so a silent failure (missing key,
// 401, throttle, unexpected response shape) is visible instead of masquerading as
// "no matches". `debug.sentBody` echoes the exact Apollo query that was built.
export interface PreviewCountResult {
  count: number
  error: string | null
  debug: {
    keyConfigured: boolean
    keyTail: string | null       // last 4 chars of the key, to identify WHICH key is in use
    endpoint: string             // the exact URL hit — verifies which build is running
    httpStatus: number | null
    rawCountField: string | null
    sentBody: unknown
  }
}

export async function previewCount(icp: Parameters<typeof buildSearchBody>[0]): Promise<PreviewCountResult> {
  const apiKey = process.env.APOLLO_API_KEY
  const body = buildSearchBody(icp, 1)
  body.per_page = 1
  const baseDebug = {
    keyConfigured: !!apiKey,
    keyTail: apiKey ? apiKey.slice(-4) : null,
    endpoint: APOLLO_PEOPLE_SEARCH,
    httpStatus: null as number | null,
    rawCountField: null as string | null,
    sentBody: body,
  }

  if (!apiKey) return { count: 0, error: 'APOLLO_API_KEY is not set on the API service', debug: baseDebug }

  try {
    const res = await fetch(APOLLO_PEOPLE_SEARCH, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'X-Api-Key': apiKey },
      body:    JSON.stringify(body),
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      return { count: 0, error: `Apollo ${res.status}: ${text.slice(0, 240)}`, debug: { ...baseDebug, httpStatus: res.status } }
    }
    // Apollo returns the match count as a top-level `total_entries` on the current
    // API; older/other shapes nest it under `pagination.total_entries`. Read both,
    // or the preview banner reports 0 for every ICP no matter how broad the query.
    const data = await res.json() as {
      total_entries?: number
      pagination?: { total_entries?: number }
    }
    const fromPagination = data.pagination?.total_entries
    const fromTop = data.total_entries
    const count = fromPagination ?? fromTop ?? 0
    const rawCountField = fromPagination != null ? 'pagination.total_entries' : fromTop != null ? 'total_entries' : 'none-found'
    return { count, error: null, debug: { ...baseDebug, httpStatus: res.status, rawCountField } }
  } catch (e) {
    return { count: 0, error: e instanceof Error ? e.message : 'preview request failed', debug: baseDebug }
  }
}

export async function searchPeopleWithFallback(
  icp: Parameters<typeof buildSearchBody>[0],
  page = 1,
): Promise<{ contacts: ApolloContact[]; relaxed: string | null }> {
  // Pass 1 — full query
  const full = buildSearchBody(icp, page)
  const contacts1 = await searchPeople(full)
  if (contacts1.length > 0) return { contacts: contacts1, relaxed: null }

  // Pass 2 — remove consent filter (consent gate was cutting the pool)
  if (icp.apollo_only_consented) {
    const relaxed2 = { ...buildSearchBody(icp, page) }
    delete relaxed2.contact_email_status
    const contacts2 = await searchPeople(relaxed2)
    if (contacts2.length > 0) {
      console.log('[apollo] fallback pass 2: removed consent filter — found', contacts2.length)
      return { contacts: contacts2, relaxed: 'Consent filter relaxed to find results. Apollo-verified emails were too restrictive for this geography.' }
    }
  }

  // Pass 3 — remove employee ranges (geo + titles only)
  const relaxed3 = { ...buildSearchBody(icp, page) }
  delete relaxed3.contact_email_status
  delete relaxed3.organization_num_employees_ranges
  const contacts3 = await searchPeople(relaxed3)
  if (contacts3.length > 0) {
    console.log('[apollo] fallback pass 3: removed size + consent filters — found', contacts3.length)
    return { contacts: contacts3, relaxed: 'Company size + consent filters relaxed to find results. Try widening the company size range in your ICP.' }
  }

  console.log('[apollo] all passes returned 0 — no contacts found for this ICP')
  return { contacts: [], relaxed: 'No contacts found even with relaxed filters. Try broader job titles or add more geographies.' }
}

export class ApolloCreditsExhaustedError extends Error {
  constructor() { super('Apollo credits exhausted — upgrade plan or wait for monthly reset') }
}

export class ApolloRateLimitError extends Error {
  constructor() { super('Apollo rate limit hit — try again in a few minutes') }
}

export async function searchPeople(body: ApolloSearchBody): Promise<ApolloContact[]> {
  const apiKey = process.env.APOLLO_API_KEY
  if (!apiKey) throw new Error('APOLLO_API_KEY env var is not set')

  const res = await fetch(APOLLO_PEOPLE_SEARCH, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json', 'X-Api-Key': apiKey },
    body:    JSON.stringify(body),
  })

  if (res.status === 429) throw new ApolloRateLimitError()

  if (!res.ok) {
    const text = await res.text()
    // Apollo returns 422 with "credits" in the message when plan is exhausted
    if (res.status === 422 && text.toLowerCase().includes('credit')) throw new ApolloCreditsExhaustedError()
    if (res.status === 402) throw new ApolloCreditsExhaustedError()
    throw new Error(`Apollo API ${res.status}: ${text}`)
  }

  const data = await res.json() as { contacts?: ApolloContact[]; people?: ApolloContact[]; error?: string }
  // Apollo free plan returns error in body with 200 when credits run out
  if (data.error?.toLowerCase().includes('credit')) throw new ApolloCreditsExhaustedError()
  return data.contacts ?? data.people ?? []
}
