#!/usr/bin/env bash
# build-playbook.sh — regenerate docs/marketing/DAILY-PLAYBOOK.md, the ONE file the
# founder's "M&V Marketing" Claude Project works from day to day.
#
# WHY GENERATED: the playbook is the calendar (MARKETING-PLAN §3b) + the launch bank
# (founder-content-playbook §6b) + the DM kit + the carousel spec, in one file — because
# the Project answers "what do I do today?" from ONE document, not four. A hand-copied
# bundle drifts the day its sources change; this script makes the mirror mechanical,
# exactly like mirror-launchpad.sh does for dots. NEVER hand-edit the output — edit the
# source doc and re-run:  bash scripts/build-playbook.sh
set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
OUT=docs/marketing/DAILY-PLAYBOOK.md

{
echo "# 🎛 M&V — THE DAILY PLAYBOOK *(GENERATED by \`scripts/build-playbook.sh\` — edit the SOURCE docs, then re-run; hand edits here are overwritten)*"
echo
echo "> **For the M&V Marketing Claude Project.** Ask *\"what do I do today?\"* with the date — the answer is the calendar row for that day plus the FULL text of that day's post, its image file and its link, all from this one file. Never write new copy when a finished piece below fits."
echo
echo "---"
echo
sed -n '/^## 3b ·/,/^## 4 ·/p' docs/marketing/MARKETING-PLAN.md | sed '$d'
echo "---"
echo
sed -n '/^## 6b ·/,/^## 7 ·/p' docs/marketing/founder-content-playbook.md | sed '$d'
echo "---"
echo
echo "# The three extra posts + every DM script *(source: warm-outreach-kit.md)*"
echo
cat docs/marketing/warm-outreach-kit.md
echo
echo "---"
echo
echo "# The carousels — the no-camera video format"
echo
echo "Three exist as finished LinkedIn-ready PDFs (produced 12 Aug: *the hour you never get back* · *why your emails never arrived* · *pay for results, not promises*). The founder uploads a PDF to LinkedIn as a **document post** with the matching post text as the caption."
echo
echo "**When asked for a NEW carousel, produce slide text in this exact shape:** 8 slides · one thought per slide · slide 1 = the hook · slides 2–7 build it · slide 8 = *\"We find your leads. You approve. That's it.\"* + get-kind.com. The founder brings the slide text to Claude Code, which renders the branded PDF."
} > "$OUT"

echo "build-playbook: wrote $OUT ($(wc -l < "$OUT") lines)"
