import os, re, sys, json

# ROOT is derived from where THIS FILE lives, never hardcoded.
#
# It used to read `ROOT = '/home/user/KIND'` — a container path that does not exist on the
# founder's Mac, so this script could not run there at all. That is the same family as #578
# (`declare -A` on bash 3.2) and #579 (BSD awk): tooling that works in the container and
# silently cannot run on the only machine that matters.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

MANIFEST = os.path.join('scripts', 'core-files.txt')
TRACE = os.path.join('scripts', '.core-trace.json')

# Seeds = the real entry points a running system starts from.
seeds = []
seeds += ['apps/api/src/index.ts', 'apps/api/src/cron.ts']
for base, pat in [('apps/portal/src/app/(milla)', None), ('apps/admin/src/app/vida', None)]:
    for dp, dn, fn in os.walk(base):
        for f in fn:
            if f in ('page.tsx','layout.tsx','route.ts'):
                seeds.append(os.path.join(dp, f))
for extra in ['apps/portal/src/middleware.ts','apps/admin/src/middleware.ts',
              'apps/portal/middleware.ts','apps/admin/middleware.ts']:
    if os.path.exists(extra): seeds.append(extra)
# The proxy Vida talks to the API through
for dp, dn, fn in os.walk('apps/admin/src/app/api'):
    for f in fn:
        if f == 'route.ts': seeds.append(os.path.join(dp, f))
for dp, dn, fn in os.walk('apps/portal/src/app/api'):
    for f in fn:
        if f == 'route.ts': seeds.append(os.path.join(dp, f))

seeds = [s for s in seeds if os.path.exists(s)]

IMPORT_RE = re.compile(r"""(?:from\s+|import\s*\(\s*)['"]([^'"]+)['"]""")
EXTS = ['.ts', '.tsx', '.js', '.jsx']

def resolve(spec, fromfile):
    cands = []
    if spec.startswith('.'):
        base = os.path.normpath(os.path.join(os.path.dirname(fromfile), spec))
        cands.append(base)
    elif spec.startswith('@/'):
        # @/ maps to <app>/src/
        parts = fromfile.split(os.sep)
        if len(parts) >= 2 and parts[0] == 'apps':
            cands.append(os.path.join('apps', parts[1], 'src', spec[2:]))
    elif spec.startswith('@kind/'):
        pkg = spec.split('/')[1]
        rest = spec[len('@kind/'+pkg):].lstrip('/')
        cands.append(os.path.join('packages', pkg, 'src', rest or 'index'))
    else:
        return None
    for c in cands:
        for e in EXTS:
            if os.path.isfile(c + e): return c + e
        for e in EXTS:
            idx = os.path.join(c, 'index' + e)
            if os.path.isfile(idx): return idx
        if os.path.isfile(c): return c
    return None

seen, queue, unresolved = set(), list(seeds), set()
while queue:
    f = queue.pop()
    if f in seen or not os.path.isfile(f): continue
    seen.add(f)
    try: src = open(f, encoding='utf-8', errors='ignore').read()
    except Exception: continue
    for spec in IMPORT_RE.findall(src):
        r = resolve(spec, f)
        if r:
            if r not in seen: queue.append(r)
        elif spec.startswith('.') or spec.startswith('@/') or spec.startswith('@kind/'):
            unresolved.add((f, spec))

core = sorted(x for x in seen if not x.endswith('.test.ts') and not x.endswith('.test.tsx'))
tests = sorted(x for x in seen if x.endswith('.test.ts') or x.endswith('.test.tsx'))
def lines(fs):
    t = 0
    for f in fs:
        try: t += sum(1 for _ in open(f, encoding='utf-8', errors='ignore'))
        except Exception: pass
    return t
core_lines = lines(core)

# WRITE THE MANIFEST. This script used to print its counts and dump a trace into a
# scratchpad path that dies with the container — it never wrote `scripts/core-files.txt`
# at all. So the manifest could not be regenerated, went stale the moment new files
# landed, and CORE-MAP.md's claim "re-run it any time; it is deterministic" was false as
# shipped. It was stale by exactly the five files Prompt 1 itself created — the
# measurement system was fenced out of the core map it shipped beside.
with open(MANIFEST, 'w', encoding='utf-8') as fh:
    fh.write('# THE OPERATIONAL CORE — machine-readable, generated by scripts/build-core-map.py\n')
    fh.write('# Every file reachable by import from a real entry point (api index+cron, every Milla\n')
    fh.write('# page, every Vida page, both middlewares, both app API proxies).\n')
    fh.write('# Anything NOT in this list is FENCED: not in play, never deleted, never edited.\n')
    fh.write(f'# {len(core)} files, {core_lines} lines. DO NOT HAND-EDIT — re-run the script.\n')
    for f in core:
        fh.write(f + '\n')

json.dump({'seeds': sorted(seeds), 'core': core, 'tests': tests,
           'unresolved': sorted(list(unresolved))[:40],
           'core_lines': core_lines}, open(TRACE, 'w'), indent=1)

print('seeds:', len(seeds), '| core files:', len(core), '| core lines:', core_lines,
      '| unresolved specs:', len(unresolved))
print('wrote:', MANIFEST, '(+', TRACE + ')')
if unresolved:
    print('UNRESOLVED IMPORTS — the graph did NOT close, do not trust these counts:', file=sys.stderr)
    for f, s in sorted(unresolved)[:20]:
        print(f'  {f} -> {s}', file=sys.stderr)
    sys.exit(1)
