[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn workspace @kind/db build && yarn workspace @kind/shared build && yarn workspace @kind/portal build"]

[start]
cmd = "yarn workspace @kind/portal start"
